name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y autoconf automake libtool

      - name: Check for configure.ac
        run: |
          if [ ! -f configure.ac ]; then
            echo "Error: configure.ac not found!"
            exit 1
          fi

      - name: Generate aclocal.m4
        run: aclocal

      - name: Add missing auxiliary files
        run: automake --add-missing --copy

      - name: Run autoreconf
        run: autoreconf --install

      - name: Generate configure script
        run: autoconf

      - name: Run configure script
        run: ./configure

      - name: Build
        run: make

      - name: Check
        run: make check

      - name: Distcheck
        run: make distcheck
